server:
  port: 8761
spring:
  security:
    user:
      name: admin
      password: pwd
logging:
  level:
    org.springframework.security: debug
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:pwd@eureka-server:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0   
management:
  endpoints:
    web:
      exposure:
        include:
        -  
